### ISSUE TITLE
Calculate func panics

### ISSUE THREAD

**Issue by afunnydev** [rylxes/go-vue-instagram#1]
Hello! Thanks for submitting the assigment. When making a request for a profile the backend panics:

```
panic: runtime error: slice bounds out of range [-1:]

goroutine 34 [running]:
my-rest-api/handlers.Calculate.func2(0xc0003a4180?)
	/home/afunnydev/inBeat/hiring/rylxes/go-instagram/handlers/stats.go:50 +0x49c
```

My feeling is that the provided cookies expired and the backend doesn't handle IG errors.

**Comment by rylxes** [comment]
Hi @afunnydev , ... thank you for this , so i have handle the errors as specified.

Then i noticed something, i think the profile page structure for instagram has changed, so the web scrapper is not working directly , so i implemented a GET request to `https://i.instagram.com/api/v1/users/web_profile_info`

Note: the previous implementation is still available

**Comment by afunnydev** [comment]
Thanks! It's been a while since I used that unofficial endpoint. Glad it still works!
